// ----------------------------------------------------------------------------
// SEED DATA - the heart of the product.
//
// Honest note: this is a hand-picked starter set so the app is useful on day
// one. Deadlines are APPROXIMATE (approx: true) and set to a representative
// next-occurrence so the countdown works. The single most important job of this
// product is keeping this data ACCURATE and GROWING. Wrong deadlines hurt the
// students who trust you - so every card links to the official site and says
// "confirm on official site".
//
// To grow this: add objects below. Later, semi-automate with a scraper + an LLM
// extraction step + a "suggest an opportunity" form users submit.
// ----------------------------------------------------------------------------

export const FIELDS = [
  "Math", "CS", "Physics", "Chemistry", "Biology",
  "Engineering", "Research", "Entrepreneurship", "Interdisciplinary",
];

export const TYPES = ["Competition", "Olympiad", "Summer Program", "Research", "Fellowship"];

export const opportunities = [
  {
    id: "usaco",
    title: "USA Computing Olympiad (USACO)",
    org: "USACO",
    type: "Olympiad",
    fields: ["CS"],
    region: "Global (online)",
    cost: "Free",
    level: "High School",
    window: "Online contests Dec-Feb; join anytime to practice",
    deadline: "2026-12-05",
    approx: true,
    url: "https://usaco.org/",
    blurb: "Four online contests a year; climb Bronze to Silver to Gold to Platinum. The main path toward the IOI.",
  },
  {
    id: "ioai",
    title: "International Olympiad in Artificial Intelligence (IOAI)",
    org: "IOAI",
    type: "Olympiad",
    fields: ["CS", "Research"],
    region: "Global",
    cost: "Free",
    level: "High School",
    window: "National selection typically winter/spring",
    deadline: "2027-02-01",
    approx: true,
    url: "https://ioai-official.org/",
    blurb: "The newest international olympiad - machine learning and AI, team-based, growing fast.",
  },
  {
    id: "usaphysics",
    title: "USA Physics Olympiad (USAPhO / F=ma)",
    org: "AAPT",
    type: "Olympiad",
    fields: ["Physics"],
    region: "US",
    cost: "Paid",
    level: "High School",
    window: "F=ma exam registration usually closes January",
    deadline: "2027-01-15",
    approx: true,
    url: "https://www.aapt.org/physicsteam/",
    blurb: "F=ma exam to USAPhO to training camp to the International Physics Olympiad team.",
  },
  {
    id: "usnco",
    title: "U.S. National Chemistry Olympiad (USNCO)",
    org: "American Chemical Society",
    type: "Olympiad",
    fields: ["Chemistry"],
    region: "US",
    cost: "Free",
    level: "High School",
    window: "Local exams typically March; register via local section",
    deadline: "2027-01-30",
    approx: true,
    url: "https://www.acs.org/education/students/highschool/olympiad.html",
    blurb: "Local to national exam to study camp to the International Chemistry Olympiad team.",
  },
  {
    id: "usabo",
    title: "USA Biology Olympiad (USABO)",
    org: "Center for Excellence in Education",
    type: "Olympiad",
    fields: ["Biology"],
    region: "US",
    cost: "Paid",
    level: "High School",
    window: "Open Exam usually February; register in fall/winter",
    deadline: "2027-02-01",
    approx: true,
    url: "https://www.usabo-trc.org/",
    blurb: "Open Exam to Semifinal to National Finals to the International Biology Olympiad.",
  },
  {
    id: "imo-path",
    title: "Math Olympiad Path (AMC to AIME to USAMO / national)",
    org: "MAA",
    type: "Olympiad",
    fields: ["Math"],
    region: "Global",
    cost: "Paid",
    level: "High School",
    window: "AMC 10/12 typically November",
    deadline: "2026-11-05",
    approx: true,
    url: "https://maa.org/maa-invitational-competitions/",
    blurb: "The classic ladder toward the International Mathematical Olympiad. Most countries run a parallel version.",
  },
  {
    id: "regeneron-sts",
    title: "Regeneron Science Talent Search",
    org: "Society for Science",
    type: "Competition",
    fields: ["Research"],
    region: "US",
    cost: "Free",
    level: "High School (seniors)",
    window: "Application usually due mid-November",
    deadline: "2026-11-11",
    approx: true,
    url: "https://www.societyforscience.org/regeneron-sts/",
    blurb: "The most prestigious pre-college research competition in the US. Original research required.",
  },
  {
    id: "isef",
    title: "Regeneron International Science and Engineering Fair (ISEF)",
    org: "Society for Science",
    type: "Competition",
    fields: ["Research", "Engineering"],
    region: "Global",
    cost: "Free",
    level: "High School",
    window: "Qualify via an affiliated fair (dates vary by region)",
    deadline: "2027-03-01",
    approx: true,
    url: "https://www.societyforscience.org/isef/",
    blurb: "The world's largest pre-college STEM research fair. Qualify through a local/affiliated fair first.",
  },
  {
    id: "yau",
    title: "S.-T. Yau High School Science Award",
    org: "Yau Award",
    type: "Research",
    fields: ["Math", "Physics", "CS", "Biology", "Chemistry"],
    region: "Global",
    cost: "Free",
    level: "High School",
    window: "Registration typically closes around September",
    deadline: "2026-09-10",
    approx: true,
    url: "https://www.yau-awards.org/",
    blurb: "Team research competition across six fields, judged by leading academics. Strong international recognition.",
  },
  {
    id: "iymc",
    title: "International Youth Math Challenge",
    org: "IYMC",
    type: "Competition",
    fields: ["Math"],
    region: "Global (online)",
    cost: "Free",
    level: "High School",
    window: "Qualification round usually August",
    deadline: "2026-08-20",
    approx: true,
    url: "https://www.iymc.info/",
    blurb: "Fully online global math competition, open to students worldwide - an easy first international contest to enter.",
  },
  {
    id: "rsi",
    title: "Research Science Institute (RSI)",
    org: "CEE & MIT",
    type: "Summer Program",
    fields: ["Research"],
    region: "US",
    cost: "Free",
    level: "High School (rising seniors)",
    window: "Application typically due mid-December to January",
    deadline: "2026-12-15",
    approx: true,
    url: "https://www.cee.org/programs/research-science-institute",
    blurb: "The most selective free summer research program in the world. Six weeks of research at MIT.",
  },
  {
    id: "promys",
    title: "PROMYS",
    org: "Boston University",
    type: "Summer Program",
    fields: ["Math"],
    region: "US",
    cost: "Paid (aid available)",
    level: "High School",
    window: "Application typically due around March",
    deadline: "2027-03-01",
    approx: true,
    url: "https://promys.org/",
    blurb: "Six intense weeks of deep number theory and problem-solving. Need-based aid available.",
  },
  {
    id: "mathcamp",
    title: "Canada/USA Mathcamp",
    org: "Mathcamp",
    type: "Summer Program",
    fields: ["Math"],
    region: "North America",
    cost: "Paid (aid available)",
    level: "High School",
    window: "Qualifying Quiz usually due March",
    deadline: "2027-03-15",
    approx: true,
    url: "https://www.mathcamp.org/",
    blurb: "Five weeks of advanced, playful mathematics. Admission via a take-home Qualifying Quiz.",
  },
  {
    id: "ssp",
    title: "Summer Science Program (SSP)",
    org: "SSP",
    type: "Summer Program",
    fields: ["Physics", "Chemistry", "Biology"],
    region: "US",
    cost: "Paid (aid available)",
    level: "High School (rising seniors)",
    window: "Application typically due February",
    deadline: "2027-02-15",
    approx: true,
    url: "https://summerscience.org/",
    blurb: "Real research in astrophysics, biochemistry, genomics, or synthetic chemistry. Legendary alumni network.",
  },
  {
    id: "mit-primes",
    title: "MIT PRIMES",
    org: "MIT",
    type: "Research",
    fields: ["Math", "CS", "Research"],
    region: "US (near Boston / online)",
    cost: "Free",
    level: "High School",
    window: "Application typically due late November / December",
    deadline: "2026-12-01",
    approx: true,
    url: "https://math.mit.edu/research/highschool/primes/",
    blurb: "Year-long research mentorship in math, CS, and computational biology. Free.",
  },
  {
    id: "simons",
    title: "Simons Summer Research Program",
    org: "Stony Brook University",
    type: "Research",
    fields: ["Research", "Engineering", "Biology"],
    region: "US",
    cost: "Stipend",
    level: "High School (rising seniors)",
    window: "Application typically due February",
    deadline: "2027-02-05",
    approx: true,
    url: "https://www.stonybrook.edu/simons/",
    blurb: "Matched with a faculty mentor for a real lab project. Students receive a stipend.",
  },
  {
    id: "bwsi",
    title: "Beaver Works Summer Institute (BWSI)",
    org: "MIT Lincoln Laboratory",
    type: "Summer Program",
    fields: ["CS", "Engineering"],
    region: "US / Online",
    cost: "Free",
    level: "High School",
    window: "Application typically due January",
    deadline: "2027-01-15",
    approx: true,
    url: "https://beaverworks.ll.mit.edu/CMS/bw/bwsi",
    blurb: "Rigorous, free, project-based programs (autonomous racing, ML, etc.) from MIT Lincoln Lab.",
  },
  {
    id: "clark",
    title: "Clark Scholars Program",
    org: "Texas Tech University",
    type: "Research",
    fields: ["Research"],
    region: "US",
    cost: "Stipend",
    level: "High School",
    window: "Application typically due mid-February",
    deadline: "2027-02-14",
    approx: true,
    url: "https://www.depts.ttu.edu/honors/academicsandenrichment/affiliatedandhighschool/clarks/",
    blurb: "Seven weeks of one-on-one research with a faculty mentor, plus a stipend. Very selective.",
  },
  {
    id: "garcia",
    title: "Garcia Summer Research Program",
    org: "Stony Brook University",
    type: "Research",
    fields: ["Engineering", "Research", "Chemistry"],
    region: "US",
    cost: "Paid",
    level: "High School",
    window: "Application typically due February",
    deadline: "2027-02-16",
    approx: true,
    url: "https://www.stonybrook.edu/garcia/",
    blurb: "Polymer and materials science research; many participants go on to enter STS and ISEF.",
  },
  {
    id: "technovation",
    title: "Technovation Girls",
    org: "Technovation",
    type: "Competition",
    fields: ["CS", "Entrepreneurship"],
    region: "Global",
    cost: "Free",
    level: "Ages 8-18",
    window: "Season registration typically opens fall; submissions spring",
    deadline: "2027-01-20",
    approx: true,
    url: "https://www.technovation.org/",
    blurb: "Girls build a mobile app and startup to solve a community problem. Global, free, beginner-friendly.",
  },
  {
    id: "diamond",
    title: "Diamond Challenge",
    org: "University of Delaware (Horn)",
    type: "Competition",
    fields: ["Entrepreneurship"],
    region: "Global",
    cost: "Free",
    level: "High School",
    window: "Registration typically closes November",
    deadline: "2026-11-12",
    approx: true,
    url: "https://diamondchallenge.org/",
    blurb: "Global high-school entrepreneurship competition with real prize funding.",
  },
  {
    id: "wharton-invest",
    title: "Wharton Global High School Investment Competition",
    org: "The Wharton School",
    type: "Competition",
    fields: ["Entrepreneurship"],
    region: "Global",
    cost: "Free",
    level: "High School",
    window: "Team registration typically closes early October",
    deadline: "2026-10-05",
    approx: true,
    url: "https://globalyouth.wharton.upenn.edu/competitions/investment-competition/",
    blurb: "Teams manage a virtual portfolio and pitch a strategy. Free, global, team-based.",
  },
  {
    id: "conrad",
    title: "Conrad Challenge",
    org: "Conrad Foundation",
    type: "Competition",
    fields: ["Engineering", "Entrepreneurship", "Interdisciplinary"],
    region: "Global",
    cost: "Free to enter",
    level: "Ages 13-18",
    window: "Activation round typically November",
    deadline: "2026-11-05",
    approx: true,
    url: "https://www.conradchallenge.org/",
    blurb: "Teams design innovations for real-world problems (space, health, energy, cyber).",
  },
  {
    id: "genes-in-space",
    title: "Genes in Space",
    org: "Genes in Space",
    type: "Competition",
    fields: ["Biology", "Research"],
    region: "US",
    cost: "Free",
    level: "Grades 7-12",
    window: "Proposal typically due February",
    deadline: "2027-02-20",
    approx: true,
    url: "https://www.genesinspace.org/",
    blurb: "Design a DNA experiment to be run aboard the International Space Station. Winning experiment actually flies.",
  },
  {
    id: "davidson",
    title: "Davidson Fellows Scholarship",
    org: "Davidson Institute",
    type: "Fellowship",
    fields: ["Research", "Math", "Interdisciplinary"],
    region: "US",
    cost: "Free",
    level: "Under 18",
    window: "Application typically due February",
    deadline: "2027-02-12",
    approx: true,
    url: "https://www.davidsongifted.org/gifted-programs/fellows-scholarship/",
    blurb: "Up to $50,000 for a significant piece of work in STEM, literature, or beyond.",
  },
  {
    id: "breakthrough-jr",
    title: "Breakthrough Junior Challenge",
    org: "Breakthrough Prize Foundation",
    type: "Competition",
    fields: ["Physics", "Math", "Biology"],
    region: "Global",
    cost: "Free",
    level: "Ages 13-18",
    window: "Submissions typically due late June",
    deadline: "2027-06-15",
    approx: true,
    url: "https://breakthroughjuniorchallenge.org/",
    blurb: "Make a short video explaining a big idea in science or math. Global, huge scholarship prize.",
  },
  {
    id: "picoctf",
    title: "picoCTF",
    org: "Carnegie Mellon University",
    type: "Competition",
    fields: ["CS"],
    region: "Global (online)",
    cost: "Free",
    level: "Middle/High School",
    window: "Main event usually March; practice gym open year-round",
    deadline: "2027-03-01",
    approx: true,
    url: "https://picoctf.org/",
    blurb: "Beginner-friendly cybersecurity capture-the-flag from CMU. Great first security competition.",
  },
  {
    id: "cyberpatriot",
    title: "CyberPatriot",
    org: "Air & Space Forces Association",
    type: "Competition",
    fields: ["CS"],
    region: "US / International divisions",
    cost: "Paid (team)",
    level: "Middle/High School",
    window: "Team registration typically closes fall",
    deadline: "2026-10-01",
    approx: true,
    url: "https://www.uscyberpatriot.org/",
    blurb: "National youth cyber-defense competition; teams harden real systems against attack.",
  },
  {
    id: "mit-think",
    title: "MIT THINK Scholars",
    org: "MIT",
    type: "Fellowship",
    fields: ["Engineering", "Research", "CS"],
    region: "Global",
    cost: "Free",
    level: "High School",
    window: "Proposal typically due January 1",
    deadline: "2027-01-01",
    approx: true,
    url: "https://think.mit.edu/",
    blurb: "Pitch a science/tech project idea; winners get funding and MIT mentorship to build it.",
  },
  {
    id: "pioneer",
    title: "Pioneer Academics Research Program",
    org: "Pioneer Academics",
    type: "Research",
    fields: ["Research", "Interdisciplinary"],
    region: "Global (online)",
    cost: "Paid (aid available)",
    level: "High School",
    window: "Rolling admissions; cohorts through the year",
    deadline: "2026-09-30",
    approx: true,
    url: "https://pioneeracademics.com/",
    blurb: "Online research with a college professor, ending in a full research paper. Fully remote.",
  },
  {
    id: "polygence",
    title: "Polygence Research Mentorship",
    org: "Polygence",
    type: "Research",
    fields: ["Research", "Interdisciplinary"],
    region: "Global (online)",
    cost: "Paid (aid available)",
    level: "High School",
    window: "Rolling; start anytime",
    deadline: "2026-10-15",
    approx: true,
    url: "https://www.polygence.org/",
    blurb: "One-on-one online research mentorship producing a project of your choice. Flexible timing.",
  },
  {
    id: "coca-cola",
    title: "Coca-Cola Scholars Program",
    org: "Coca-Cola Scholars Foundation",
    type: "Fellowship",
    fields: ["Interdisciplinary"],
    region: "US",
    cost: "Free",
    level: "High School (seniors)",
    window: "Application typically closes end of October",
    deadline: "2026-10-31",
    approx: true,
    url: "https://www.coca-colascholarsfoundation.org/",
    blurb: "A $20,000 leadership scholarship for graduating seniors. Broad, achievement-based.",
  },
  {
    id: "kaggle",
    title: "Kaggle Competitions",
    org: "Kaggle (Google)",
    type: "Competition",
    fields: ["CS", "Research"],
    region: "Global (online)",
    cost: "Free",
    level: "Any",
    window: "New competitions launch continuously",
    deadline: "2026-09-01",
    approx: true,
    url: "https://www.kaggle.com/competitions",
    blurb: "Real machine-learning competitions with leaderboards and prizes. Start any time, build a public track record.",
  },
  {
    id: "iris",
    title: "International Research Olympiad (IRO)",
    org: "IRO",
    type: "Competition",
    fields: ["Research"],
    region: "Global (online)",
    cost: "Free",
    level: "High School",
    window: "Rounds through winter/spring; finals in summer",
    deadline: "2027-01-10",
    approx: true,
    url: "https://internationalresearcholympiad.org/",
    blurb: "Tests research ability and critical thinking across rounds; finalists present at a summit.",
  },
  {
    id: "spaceport",
    title: "NASA / Local University Research & Internships",
    org: "Various (e.g., NASA, national labs)",
    type: "Research",
    fields: ["Research", "Engineering", "Physics"],
    region: "Varies",
    cost: "Stipend",
    level: "High School / Undergrad",
    window: "Deadlines vary widely by program - set your own reminder",
    deadline: "2026-11-01",
    approx: true,
    url: "https://intern.nasa.gov/",
    blurb: "A reminder to hunt local university labs and national programs near you - often the best-kept secret.",
  },
];
