// ---------------------------------------------------------------------------
// INDIA SET - BATCH 2
//
// Same verification rules as opportunities.india.js. Kept in a separate file
// purely to keep each file reviewable; both are merged by lib/india.js.
// ---------------------------------------------------------------------------

export const indiaOpportunities2 = [
  {
    id: "yuvika",
    title: "YUVIKA - Yuva Vigyani Karyakram (Young Scientist Programme)",
    org: "ISRO",
    type: "Summer Program",
    fields: ["Physics", "Engineering", "Research"],
    region: "India",
    cost: "Free (fully funded)",
    level: "Class 9 (as per recent cycles)",
    window: "Residential programme usually in May; applications typically open around February-March",
    deadline: "2027-03-01",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.isro.gov.in/",
    url: "https://www.isro.gov.in/",
    eligibility: { grades: "9 (check current cycle)", nationality: "India", selection: "state/board quota by academic performance and extracurriculars" },
    components: ["Online application", "Class 8 marks", "Extracurricular record"],
    blurb: "Two weeks at an ISRO centre as a school student - fully funded, travel included. One of the most sought-after school programmes in the country and heavily quota-based, so apply the moment it opens.",
  },
  {
    id: "vvm",
    title: "Vidyarthi Vigyan Manthan (VVM)",
    org: "Vijnana Bharati with NCERT & DST",
    type: "Competition",
    fields: ["Physics", "Chemistry", "Biology", "Interdisciplinary"],
    region: "India",
    cost: "Modest fee",
    level: "Classes 6-11",
    window: "Registration usually opens mid-year; first-level exam around November",
    deadline: "2026-10-31",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://vvm.org.in/",
    url: "https://vvm.org.in/",
    eligibility: { grades: "6-11", nationality: "India" },
    components: ["Online registration", "Computer-based exam"],
    blurb: "India's largest science talent search by participation. Winners get camps at national labs and mentoring - an unusually good return for a low-barrier exam.",
  },
  {
    id: "homi-bhabha-balvaidnyanik",
    title: "Dr. Homi Bhabha Balvaidnyanik Competition",
    org: "Greater Bombay Science Teachers' Association",
    type: "Competition",
    fields: ["Physics", "Chemistry", "Biology"],
    region: "India (Maharashtra-centred)",
    cost: "Modest fee",
    level: "Classes 6 and 9",
    window: "Written exam usually early in the year; registration through schools beforehand",
    deadline: "2026-10-31",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://mumbaiscience.org/",
    url: "https://mumbaiscience.org/",
    eligibility: { grades: "6 and 9 only", enrolVia: "school" },
    components: ["Written exam", "Practical round", "Interview for finalists"],
    blurb: "A three-stage contest with a genuine practical and interview round - rare at school level, and excellent preparation for olympiad-style assessment.",
  },
  {
    id: "e-yantra",
    title: "e-Yantra Robotics Competition (eYRC)",
    org: "IIT Bombay (MoE funded)",
    type: "Competition",
    fields: ["Engineering", "CS"],
    region: "India",
    cost: "Free",
    level: "Undergrad / Diploma",
    window: "Registration usually opens around August-September; runs across the academic year",
    deadline: "2026-09-15",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://e-yantra.org/",
    url: "https://e-yantra.org/",
    eligibility: { level: "Engineering/diploma undergraduates", team: "teams of up to 4", nationality: "India" },
    components: ["Team registration through your college", "Online qualifier task"],
    blurb: "A months-long robotics competition run from IIT Bombay, free, with hardware provided to selected teams. Strong internship pipeline attached.",
  },
  {
    id: "inctf-junior",
    title: "InCTF Junior",
    org: "Amrita Vishwa Vidyapeetham (team bi0s)",
    type: "Competition",
    fields: ["CS"],
    region: "India",
    cost: "Free",
    level: "School students",
    window: "Rounds usually run across the academic year",
    deadline: "2026-11-30",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://junior.inctf.in/",
    url: "https://junior.inctf.in/",
    eligibility: { grades: "school", nationality: "India" },
    components: ["Online registration", "Capture-the-flag rounds"],
    blurb: "India's national cybersecurity capture-the-flag for school students, from the team behind one of the country's top CTF groups. Beginner-friendly entry rounds.",
  },
  {
    id: "hcl-jigsaw",
    title: "HCL Jigsaw",
    org: "HCLTech",
    type: "Competition",
    fields: ["Math", "Interdisciplinary"],
    region: "India",
    cost: "Free",
    level: "Classes 6-9",
    window: "Registration usually mid-year, rounds across the academic year",
    deadline: "2026-09-30",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.hcljigsaw.com/",
    url: "https://www.hcljigsaw.com/",
    eligibility: { grades: "6-9", nationality: "India" },
    components: ["Online registration", "Aptitude and reasoning rounds"],
    blurb: "A reasoning and critical-thinking contest for middle schoolers with scholarships for winners. Good early entry point before the olympiad ladder.",
  },
  {
    id: "green-olympiad",
    title: "GREEN Olympiad",
    org: "TERI (The Energy and Resources Institute)",
    type: "Olympiad",
    fields: ["Biology", "Interdisciplinary"],
    region: "India / International",
    cost: "Modest fee",
    level: "Classes 4-12",
    window: "Exam usually in the second half of the year; school registration beforehand",
    deadline: "2026-09-30",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://greenolympiad.teriin.org/",
    url: "https://greenolympiad.teriin.org/",
    eligibility: { grades: "4-12", enrolVia: "school" },
    components: ["School registration", "Written exam"],
    blurb: "An environment-focused olympiad from TERI, running for decades. An easy first national exam, especially for younger students.",
  },
  {
    id: "sof-nso",
    title: "SOF National Science Olympiad (NSO)",
    org: "Science Olympiad Foundation",
    type: "Olympiad",
    fields: ["Physics", "Chemistry", "Biology"],
    region: "India",
    cost: "Modest fee",
    level: "Classes 1-12",
    window: "School-conducted exams, usually in the second half of the year",
    deadline: "2026-11-30",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.sofworld.org/",
    url: "https://www.sofworld.org/",
    eligibility: { grades: "1-12", enrolVia: "school only" },
    components: ["Registration through your school (individual entry not accepted)"],
    blurb: "A very widely taken school olympiad. Worth knowing: it is not connected to the HBCSE national olympiad path that leads to international teams.",
  },
  {
    id: "sof-imo-math",
    title: "SOF International Mathematics Olympiad (IMO by SOF)",
    org: "Science Olympiad Foundation",
    type: "Olympiad",
    fields: ["Math"],
    region: "India",
    cost: "Modest fee",
    level: "Classes 1-12",
    window: "School-conducted exams, usually in the second half of the year",
    deadline: "2026-11-30",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.sofworld.org/",
    url: "https://www.sofworld.org/",
    eligibility: { grades: "1-12", enrolVia: "school only" },
    components: ["Registration through your school"],
    blurb: "Commonly confused with the actual International Mathematical Olympiad - it is not the same thing. For the IMO team path, start at IOQM instead.",
  },
  {
    id: "sof-nco",
    title: "SOF National Cyber Olympiad (NCO)",
    org: "Science Olympiad Foundation",
    type: "Olympiad",
    fields: ["CS"],
    region: "India",
    cost: "Modest fee",
    level: "Classes 1-12",
    window: "School-conducted exams, usually in the second half of the year",
    deadline: "2026-11-30",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.sofworld.org/",
    url: "https://www.sofworld.org/",
    eligibility: { grades: "1-12", enrolVia: "school only" },
    components: ["Registration through your school"],
    blurb: "A computers and logical-reasoning olympiad taken through schools. An accessible starting point, but not a route to the informatics olympiad team.",
  },
  {
    id: "nstse",
    title: "National Level Science Talent Search Examination (NSTSE)",
    org: "Unified Council",
    type: "Competition",
    fields: ["Physics", "Chemistry", "Biology", "Math"],
    region: "India",
    cost: "Modest fee",
    level: "Classes 1-12",
    window: "Exam usually early in the year; registration through schools beforehand",
    deadline: "2026-12-15",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.unifiedcouncil.com/",
    url: "https://www.unifiedcouncil.com/",
    eligibility: { grades: "1-12", enrolVia: "school or individual" },
    components: ["Registration", "Diagnostic exam"],
    blurb: "A diagnostic talent exam that reports where your conceptual gaps are, not just a rank. The feedback report is the actual value here.",
  },
  {
    id: "ashoka-ysp",
    title: "Ashoka Young Scholars Programme (YSP)",
    org: "Ashoka University",
    type: "Summer Program",
    fields: ["Interdisciplinary", "Research"],
    region: "India (Sonipat)",
    cost: "Paid (aid may be available)",
    level: "High School",
    window: "Two-week editions usually in May and June; applications open earlier in the year",
    deadline: "2027-03-31",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.ashoka.edu.in/ysp/",
    url: "https://www.ashoka.edu.in/ysp/",
    eligibility: { level: "High school students", nationality: "open" },
    components: ["Online application", "Statement of interest"],
    blurb: "A residential taste of liberal-arts-style university learning with Ashoka faculty. Two editions each summer, so pick the dates that fit.",
  },
  {
    id: "inacc",
    title: "Indian National Aerospace & CANSAT Challenge (INACC)",
    org: "INACC",
    type: "Competition",
    fields: ["Engineering", "Physics"],
    region: "India",
    cost: "Paid (team)",
    level: "School / Undergrad",
    window: "Annual challenge with design and launch stages",
    deadline: "2026-12-31",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.inacc.in/",
    url: "https://www.inacc.in/",
    eligibility: { level: "School and college teams", team: true, nationality: "India" },
    components: ["Team registration", "Design report", "Working CanSat payload"],
    blurb: "Build and launch a soda-can-sized satellite payload. One of the few Indian competitions where school students do real aerospace engineering.",
  },
  {
    id: "vigyan-jyoti",
    title: "Vigyan Jyoti",
    org: "Department of Science & Technology, Government of India",
    type: "Summer Program",
    fields: ["Physics", "Chemistry", "Biology", "Math", "Engineering"],
    region: "India",
    cost: "Free",
    level: "Classes 9-12 (girls)",
    window: "Runs through the academic year via participating districts and schools",
    deadline: "2026-09-30",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://dst.gov.in/",
    url: "https://dst.gov.in/",
    eligibility: { grades: "9-12", gender: "girls", nationality: "India", route: "participating schools/districts" },
    components: ["Selection through your school or district node"],
    blurb: "A government programme for girls in classes 9-12 to pursue STEM: mentorship, campus visits, counselling and exposure to careers in science.",
  },
  {
    id: "pmrbp",
    title: "Pradhan Mantri Rashtriya Bal Puraskar (PMRBP)",
    org: "Ministry of Women & Child Development, Government of India",
    type: "Fellowship",
    fields: ["Interdisciplinary", "Research", "Engineering"],
    region: "India",
    cost: "Free",
    level: "Ages 5-18",
    window: "Nominations usually invited in the second half of the year; awards announced around Republic Day",
    deadline: "2026-10-31",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://awards.gov.in/",
    url: "https://awards.gov.in/",
    eligibility: { ages: "5-18", nationality: "India", categories: "innovation, science & technology, social service, art, sports, bravery" },
    components: ["Self-nomination or nomination via the national awards portal", "Evidence of achievement"],
    blurb: "India's national award for exceptional children, including a science and innovation category. Self-nomination is allowed - most eligible students never realise that.",
  },
  {
    id: "iisf",
    title: "India International Science Festival (IISF) student events",
    org: "Ministry of Science & Technology with Vijnana Bharati",
    type: "Competition",
    fields: ["Interdisciplinary", "Research"],
    region: "India",
    cost: "Free",
    level: "School / Undergrad",
    window: "Annual festival with student competitions; usually announced a few months ahead",
    deadline: "2026-11-15",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.scienceindiafest.org/",
    url: "https://www.scienceindiafest.org/",
    eligibility: { level: "School and college students", nationality: "India" },
    components: ["Event-specific registration"],
    blurb: "A national science festival with student competitions, record attempts and exhibitions attached. Low barrier, and a good first national-level exposure.",
  },
  {
    id: "iitb-summer-fellowship",
    title: "IIT Bombay Summer Research Internship / Fellowship",
    org: "IIT Bombay",
    type: "Research",
    fields: ["Engineering", "CS", "Physics", "Research"],
    region: "India",
    cost: "Stipend",
    level: "Undergrad",
    window: "Applications usually open around January-February for a summer placement",
    deadline: "2027-02-15",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.iitb.ac.in/",
    url: "https://www.iitb.ac.in/",
    eligibility: { level: "Undergraduate students", nationality: "India" },
    components: ["Online application", "Academic record", "Faculty match"],
    blurb: "Summer research with IIT Bombay faculty. Most IITs run an equivalent - apply to several, since each has its own portal and deadline.",
  },
];
