// ---------------------------------------------------------------------------
// INDIA SET
//
// Goal: be THE complete map for an Indian STEM student. Target is 200+.
// This is an honest work-in-progress - see the verification fields below.
//
// VERIFICATION MODEL (read this before adding anything):
//   verifiedAt   - the date a human last checked this entry against the
//                  official source. Stale = untrustworthy. Re-check yearly,
//                  and always before a cycle opens.
//   sourceUrl    - the exact page that states the deadline. Not the homepage.
//   approx: true - the deadline is a PATTERN-BASED ESTIMATE from previous
//                  cycles, not a confirmed date. The UI must never show a
//                  hard countdown for these without flagging them.
//   approx:false - confirmed against the official source on verifiedAt.
//
// The single most damaging thing this product can do is give a student a
// wrong date they trusted. When unsure, widen the window and mark approx.
//
// EXTRA FIELDS (additive - safe for the UI to ignore):
//   eligibility  - structured, for real matching later
//   leadsTo      - the next stage in a pathway (opportunities are ladders,
//                  not flat lists: IOQM -> RMO -> INMO -> IMO)
//   components   - what the application actually requires; this is the input
//                  the paid application builder will consume
// ---------------------------------------------------------------------------

export const indiaOpportunities = [
  // ======================= NATIONAL OLYMPIADS =======================
  {
    id: "ioqm",
    title: "Indian Olympiad Qualifier in Mathematics (IOQM)",
    org: "MTA India & HBCSE",
    type: "Olympiad",
    fields: ["Math"],
    region: "India",
    cost: "Paid (modest fee)",
    level: "Classes 8-12",
    window: "Exam early September; registration usually closes late July",
    deadline: "2026-07-25",
    approx: false,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://ioqm.mtai.org.in/",
    url: "https://ioqm.mtai.org.in/",
    eligibility: { grades: "8-12", nationality: "India", team: false },
    leadsTo: "rmo",
    components: ["Centre or online enrolment", "Fee payment"],
    blurb: "Stage one of India's Math Olympiad path. The widest funnel: clear it and you are in the top few percent nationally.",
  },
  {
    id: "rmo",
    title: "Regional Mathematical Olympiad (RMO)",
    org: "HBCSE",
    type: "Olympiad",
    fields: ["Math"],
    region: "India",
    cost: "Free (for qualifiers)",
    level: "Classes 8-12",
    window: "Usually October; entry is by qualifying through IOQM",
    deadline: "2026-10-15",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://olympiads.hbcse.tifr.res.in/",
    url: "https://olympiads.hbcse.tifr.res.in/",
    eligibility: { grades: "8-12", nationality: "India", prerequisite: "IOQM qualification" },
    leadsTo: "inmo",
    components: ["Qualify via IOQM"],
    blurb: "The second stage: six proof-based problems. You cannot apply directly - you get here by clearing IOQM.",
  },
  {
    id: "inmo",
    title: "Indian National Mathematical Olympiad (INMO)",
    org: "HBCSE",
    type: "Olympiad",
    fields: ["Math"],
    region: "India",
    cost: "Free (for qualifiers)",
    level: "Classes 8-12",
    window: "Usually January; entry by qualifying through RMO",
    deadline: "2027-01-17",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://olympiads.hbcse.tifr.res.in/",
    url: "https://olympiads.hbcse.tifr.res.in/",
    eligibility: { grades: "8-12", nationality: "India", prerequisite: "RMO qualification" },
    leadsTo: "imotc",
    components: ["Qualify via RMO"],
    blurb: "The national stage. Top performers go to the training camp that selects India's IMO and EGMO teams.",
  },
  {
    id: "imotc",
    title: "IMO Training Camp (IMOTC)",
    org: "HBCSE",
    type: "Summer Program",
    fields: ["Math"],
    region: "India",
    cost: "Free (fully funded)",
    level: "INMO qualifiers",
    window: "Usually April-May; invitation only",
    deadline: "2027-04-01",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://olympiads.hbcse.tifr.res.in/",
    url: "https://olympiads.hbcse.tifr.res.in/",
    eligibility: { prerequisite: "INMO qualification", nationality: "India" },
    components: ["Invitation only"],
    blurb: "Intensive residential training for the top INMO scorers. The final filter before India's international math teams.",
  },
  {
    id: "ioq-science",
    title: "Indian Olympiad Qualifier in Science (Physics, Chemistry, Biology, Astronomy)",
    org: "IAPT & HBCSE",
    type: "Olympiad",
    fields: ["Physics", "Chemistry", "Biology"],
    region: "India",
    cost: "Paid (per subject)",
    level: "Classes up to 12",
    window: "School enrolment usually August-September",
    deadline: "2026-09-14",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://olympiads.hbcse.tifr.res.in/",
    url: "https://olympiads.hbcse.tifr.res.in/",
    eligibility: { grades: "up to 12", nationality: "India", enrolVia: "school or approved centre" },
    leadsTo: "ino",
    components: ["School/centre enrolment", "Fee per subject"],
    blurb: "The national gateway into the Physics, Chemistry, Biology and Astronomy Olympiads. Enrol through your school - many schools miss the window.",
  },
  {
    id: "ino",
    title: "Indian National Olympiad (INO) - Physics, Chemistry, Biology, Astronomy, Junior Science",
    org: "HBCSE",
    type: "Olympiad",
    fields: ["Physics", "Chemistry", "Biology"],
    region: "India",
    cost: "Free (for qualifiers)",
    level: "IOQ qualifiers",
    window: "Usually late January/February; separate mandatory registration on the HBCSE portal",
    deadline: "2027-01-17",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://olympiads.hbcse.tifr.res.in/science-olympiad-2025-2026/",
    url: "https://olympiads.hbcse.tifr.res.in/",
    eligibility: { prerequisite: "IOQ qualification", nationality: "India" },
    leadsTo: "ocsc",
    components: ["Mandatory separate registration on HBCSE portal - missing it means disqualification"],
    blurb: "Stage two of the science olympiads. Critical detail: qualifying is not enough, you must separately register on the HBCSE portal or you are disqualified.",
  },
  {
    id: "ocsc",
    title: "Orientation-cum-Selection Camp (OCSC)",
    org: "HBCSE",
    type: "Summer Program",
    fields: ["Physics", "Chemistry", "Biology"],
    region: "India",
    cost: "Free (fully funded)",
    level: "INO qualifiers",
    window: "Usually April-June; invitation only",
    deadline: "2027-04-15",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://olympiads.hbcse.tifr.res.in/",
    url: "https://olympiads.hbcse.tifr.res.in/",
    eligibility: { prerequisite: "INO qualification", nationality: "India" },
    components: ["Invitation only"],
    blurb: "Residential camp at HBCSE with real lab work. Selects the students who represent India at IPhO, IChO, IBO and IOAA.",
  },
  {
    id: "ico-india",
    title: "Indian Computing Olympiad (ZIO / ZCO to INOI)",
    org: "IARCS",
    type: "Olympiad",
    fields: ["CS"],
    region: "India",
    cost: "Paid (modest fee)",
    level: "Classes up to 12",
    window: "Zonal round usually November; registration usually closes late October",
    deadline: "2026-10-30",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.iarcs.org.in/inoi/",
    url: "https://www.iarcs.org.in/inoi/",
    eligibility: { grades: "up to 12", nationality: "India", anyBoard: true, minAge: "none" },
    leadsTo: "inoi",
    components: ["Online registration", "Fee payment"],
    blurb: "Clear ZIO (reasoning, pen and paper) or ZCO (actual coding) to reach INOI. Open to any board, no lower age limit.",
  },
  {
    id: "inoi",
    title: "Indian National Olympiad in Informatics (INOI)",
    org: "IARCS",
    type: "Olympiad",
    fields: ["CS"],
    region: "India",
    cost: "Free (for qualifiers)",
    level: "ZIO/ZCO qualifiers",
    window: "Usually February; entry by clearing ZIO or ZCO",
    deadline: "2027-02-13",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.iarcs.org.in/inoi/",
    url: "https://www.iarcs.org.in/inoi/",
    eligibility: { prerequisite: "ZIO or ZCO qualification", nationality: "India", notInCollege: true },
    leadsTo: "ioitc",
    components: ["Qualify via ZIO or ZCO", "Working C++"],
    blurb: "Two algorithmic problems in three hours, in C++. Around 30 students advance to the IOI training camp.",
  },
  {
    id: "ioitc",
    title: "IOI Training Camp (IOITC)",
    org: "IARCS",
    type: "Summer Program",
    fields: ["CS"],
    region: "India",
    cost: "Free (sponsored)",
    level: "INOI qualifiers",
    window: "Usually mid-year; invitation only",
    deadline: "2027-05-01",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.iarcs.org.in/inoi/",
    url: "https://www.iarcs.org.in/inoi/",
    eligibility: { prerequisite: "INOI qualification" },
    components: ["Invitation only"],
    blurb: "Intensive camp with mock contests that selects the four students representing India at the IOI.",
  },
  {
    id: "inaio",
    title: "Indian National AI Olympiad (INAIO)",
    org: "ACM India",
    type: "Olympiad",
    fields: ["CS", "Research"],
    region: "India",
    cost: "Free / modest fee",
    level: "School students",
    window: "Rounds typically winter; leads to the IOAI team",
    deadline: "2026-12-15",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.iarcs.org.in/inoi/",
    url: "https://inaio.acm.org/",
    eligibility: { grades: "school", nationality: "India" },
    components: ["Online registration", "ML fundamentals"],
    blurb: "India's selection path for the International Olympiad in Artificial Intelligence. New, growing fast, and far less crowded than the older olympiads.",
  },

  // ======================= RESEARCH & FELLOWSHIPS =======================
  {
    id: "srfp",
    title: "Science Academies' Summer Research Fellowship (SRFP)",
    org: "IAS Bengaluru, INSA, NASI",
    type: "Research",
    fields: ["Research", "Physics", "Chemistry", "Biology", "Math"],
    region: "India",
    cost: "Stipend",
    level: "Undergrad / Postgrad",
    window: "Two-month summer placement; applications usually close end of January",
    deadline: "2027-01-31",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://webjapps.ias.ac.in/fellowship2026/index.html",
    url: "https://web-japps.ias.ac.in/",
    eligibility: { level: "UG/PG at UGC/AICTE recognised institutions", nationality: "India", teachersAlsoEligible: true },
    components: ["Online application", "Academic marks", "Referee email (a teacher familiar with your work)"],
    blurb: "The highest-signal summer research placement in India: two months with a scientist from the national academies' network. Open to students at any recognised college.",
  },
  {
    id: "jncasr-srfp",
    title: "JNCASR Summer Research Fellowship",
    org: "JNCASR, Bengaluru",
    type: "Research",
    fields: ["Research", "Chemistry", "Biology", "Physics", "Engineering"],
    region: "India",
    cost: "Stipend + travel support",
    level: "Bachelor's / Master's",
    window: "Two months of training; applications usually open winter",
    deadline: "2027-01-15",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.jncasr.ac.in/academic/fandeprogrammes/srfp",
    url: "https://www.jncasr.ac.in/academic/fandeprogrammes/srfp",
    eligibility: { level: "Bachelor's or Master's in science/engineering", nationality: "India" },
    components: ["Online application", "Merit-based selection"],
    blurb: "Running since 1991 with thousands of alumni. Two months in life, chemical, physical sciences or engineering, with a monthly fellowship and travel support.",
  },
  {
    id: "tifr-vsrp",
    title: "TIFR Visiting Students Research Programme (VSRP)",
    org: "Tata Institute of Fundamental Research",
    type: "Research",
    fields: ["Research", "Physics", "Math", "Biology", "CS"],
    region: "India",
    cost: "Stipend",
    level: "Final-year BSc / MSc / BTech",
    window: "Summer placement; applications usually close end of January",
    deadline: "2027-01-31",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.tifrh.res.in/academics/vsrp/",
    url: "https://www.tifr.res.in/",
    eligibility: { level: "Final year 3-yr BSc, or pre-final/final year MSc, Int MSc, 4-yr BSc, BTech/BE", phdNotEligible: true, repeatNotEligible: true },
    components: ["Online application", "Academic record"],
    blurb: "Research at one of India's premier institutes. Note the hard rules: no PhD students, and previous participants cannot reapply.",
  },
  {
    id: "nius",
    title: "National Initiative on Undergraduate Science (NIUS)",
    org: "HBCSE, TIFR",
    type: "Research",
    fields: ["Physics", "Chemistry", "Biology", "Research"],
    region: "India",
    cost: "Free (supported)",
    level: "Undergrad",
    window: "Nurture camps and research projects; calls usually announced through the year",
    deadline: "2026-12-01",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.hbcse.tifr.res.in/",
    url: "https://www.hbcse.tifr.res.in/",
    eligibility: { level: "Undergraduate science students", nationality: "India" },
    components: ["Application with academic record", "Statement of interest"],
    blurb: "Long-term undergraduate research engagement from HBCSE - camps plus a sustained project, not a one-off summer.",
  },
  {
    id: "iisc-summer-internship",
    title: "IISc Summer Research Internships",
    org: "Indian Institute of Science, Bengaluru",
    type: "Research",
    fields: ["Research", "Engineering", "Physics", "Biology", "CS"],
    region: "India",
    cost: "Varies (some stipend)",
    level: "Undergrad",
    window: "Mostly via SRFP or by writing directly to faculty; timing varies by department",
    deadline: "2027-01-31",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.iisc.ac.in/",
    url: "https://www.iisc.ac.in/",
    eligibility: { level: "Undergraduate", nationality: "India" },
    components: ["Often a direct email to a faculty member with CV and a specific research interest"],
    blurb: "India's top research institute. Many placements happen through SRFP or a well-written cold email to a professor - the second route is badly underused.",
  },
  {
    id: "iiser-summer",
    title: "IISER Summer Student Programme",
    org: "IISERs (Pune, Kolkata, Mohali, Bhopal, Thiruvananthapuram, Tirupati, Berhampur)",
    type: "Research",
    fields: ["Research", "Physics", "Chemistry", "Biology", "Math"],
    region: "India",
    cost: "Stipend (varies by campus)",
    level: "Undergrad",
    window: "Summer projects; each campus runs its own call, usually announced Dec-Feb",
    deadline: "2027-02-15",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.iiserpune.ac.in/",
    url: "https://www.iiserpune.ac.in/",
    eligibility: { level: "Undergraduate science students", nationality: "India" },
    components: ["Campus-specific application", "Academic transcript"],
    blurb: "Each IISER campus runs its own summer research programme with separate deadlines - check several, not just the nearest one.",
  },
  {
    id: "iucaa-vsp",
    title: "IUCAA Visiting Students Programme",
    org: "Inter-University Centre for Astronomy and Astrophysics, Pune",
    type: "Research",
    fields: ["Physics", "Research"],
    region: "India",
    cost: "Stipend",
    level: "Undergrad / Postgrad",
    window: "Summer and winter batches; calls usually announced a few months ahead",
    deadline: "2027-01-31",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.iucaa.in/",
    url: "https://www.iucaa.in/",
    eligibility: { level: "UG/PG in physics or astronomy", nationality: "India" },
    components: ["Application", "Recommendation"],
    blurb: "Astronomy and astrophysics research for students, at India's dedicated centre for the field.",
  },
  {
    id: "iia-vsp",
    title: "Indian Institute of Astrophysics Visiting Students Programme",
    org: "Indian Institute of Astrophysics, Bengaluru",
    type: "Research",
    fields: ["Physics", "Research"],
    region: "India",
    cost: "Stipend",
    level: "Undergrad / Postgrad",
    window: "Summer projects; call usually announced early in the year",
    deadline: "2027-02-15",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.iiap.res.in/",
    url: "https://www.iiap.res.in/",
    eligibility: { level: "UG/PG in physics or astronomy", nationality: "India" },
    components: ["Application", "Academic record"],
    blurb: "Hands-on astrophysics research including access to observatory facilities.",
  },
  {
    id: "rri-vsp",
    title: "Raman Research Institute Visiting Students Programme",
    org: "Raman Research Institute, Bengaluru",
    type: "Research",
    fields: ["Physics", "Research"],
    region: "India",
    cost: "Stipend",
    level: "Undergrad / Postgrad",
    window: "Summer research; call usually announced early in the year",
    deadline: "2027-02-01",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.rri.res.in/",
    url: "https://www.rri.res.in/",
    eligibility: { level: "UG/PG", nationality: "India" },
    components: ["Application", "Statement of purpose"],
    blurb: "Physics research across astronomy, soft matter and quantum information at a storied Bengaluru institute.",
  },
  {
    id: "imsc-summer",
    title: "IMSc Summer Research Programme",
    org: "Institute of Mathematical Sciences, Chennai",
    type: "Research",
    fields: ["Math", "Physics", "CS", "Research"],
    region: "India",
    cost: "Stipend",
    level: "Undergrad / Postgrad",
    window: "Summer projects; applications usually early in the year",
    deadline: "2027-02-01",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.imsc.res.in/",
    url: "https://www.imsc.res.in/",
    eligibility: { level: "UG/PG in math, physics or CS", nationality: "India" },
    components: ["Application", "Academic record"],
    blurb: "Theoretical research in mathematics, theoretical physics and theoretical computer science.",
  },
  {
    id: "icts-summer",
    title: "ICTS Summer Research Programme",
    org: "International Centre for Theoretical Sciences, Bengaluru",
    type: "Research",
    fields: ["Physics", "Math", "Research"],
    region: "India",
    cost: "Stipend",
    level: "Undergrad / Postgrad",
    window: "Summer projects and programmes through the year",
    deadline: "2027-02-01",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.icts.res.in/",
    url: "https://www.icts.res.in/",
    eligibility: { level: "UG/PG", nationality: "India" },
    components: ["Application", "Recommendation"],
    blurb: "Theoretical physics and mathematics, plus a steady stream of open schools and workshops worth attending on their own.",
  },
  {
    id: "ncbs-summer",
    title: "NCBS Summer Research Programme",
    org: "National Centre for Biological Sciences, Bengaluru",
    type: "Research",
    fields: ["Biology", "Research"],
    region: "India",
    cost: "Stipend",
    level: "Undergrad / Postgrad",
    window: "Summer lab placements; applications usually close early in the year",
    deadline: "2027-01-31",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.ncbs.res.in/",
    url: "https://www.ncbs.res.in/",
    eligibility: { level: "UG/PG in biology or allied sciences", nationality: "India" },
    components: ["Application", "Statement of interest", "Recommendation"],
    blurb: "One of India's best places to do real biology as a student, in working research labs.",
  },

  // ======================= COMPETITIONS =======================
  {
    id: "iris-national-fair",
    title: "IRIS National Fair",
    org: "EXSTEMPLAR Education Linkers Foundation (with DST)",
    type: "Competition",
    fields: ["Research", "Engineering", "Interdisciplinary"],
    region: "India",
    cost: "Free to enter",
    level: "Classes 5-12",
    window: "Abstract submission usually autumn; national fair around January/February",
    deadline: "2026-10-15",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.irisnationalfair.org/",
    url: "https://www.irisnationalfair.org/",
    eligibility: { grades: "5-12", nationality: "Indian-origin, studying in schools in India", team: "individual or exactly 2" },
    leadsTo: "isef",
    components: ["Online abstract/synopsis", "Original research with experimental data, or a novel engineering improvement", "Research data no older than 12 months"],
    blurb: "India's official pathway to Regeneron ISEF, the world's largest pre-college science fair. Running since 2006 and far less known inside India than it deserves.",
  },
  {
    id: "technothlon",
    title: "Technothlon",
    org: "IIT Guwahati (Techniche)",
    type: "Competition",
    fields: ["Interdisciplinary", "Math", "CS"],
    region: "India",
    cost: "Paid (small team fee)",
    level: "Classes 9-12",
    window: "Prelims usually July across 450+ cities; Mains at IIT Guwahati during Techniche",
    deadline: "2027-06-20",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://technothlon.techniche.org.in/",
    url: "https://technothlon.techniche.org.in/",
    eligibility: { grades: "9-12", team: "exactly 2", squads: "Junior (9-10) and Senior (11-12)" },
    components: ["Team of two", "Registration fee", "No syllabus - pure logic and reasoning"],
    blurb: "A logic championship with no syllabus and nothing to memorise. Team of two, prelims in your own city. One of the most accessible national contests in India.",
  },
  {
    id: "inspire-manak",
    title: "INSPIRE Awards - MANAK",
    org: "Department of Science & Technology, Government of India",
    type: "Competition",
    fields: ["Engineering", "Interdisciplinary", "Entrepreneurship"],
    region: "India",
    cost: "Free",
    level: "Classes 6-12",
    window: "School nominations usually close mid-September",
    deadline: "2026-09-15",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.inspireawards-dst.gov.in/",
    url: "https://www.inspireawards-dst.gov.in/",
    eligibility: { grades: "6-12", nationality: "India", nominatedVia: "school (max 5 ideas per school)" },
    components: ["An original innovation idea", "Nomination through your school"],
    blurb: "Submit an innovation idea through your school; selected students receive a cash award to build a prototype. One of the widest-reach government schemes, and most students never hear of it.",
  },
  {
    id: "ncsc",
    title: "National Children's Science Congress (NCSC)",
    org: "NCSTC, Department of Science & Technology",
    type: "Competition",
    fields: ["Research", "Interdisciplinary", "Biology"],
    region: "India",
    cost: "Free",
    level: "Ages 10-17",
    window: "District and state rounds usually autumn, national congress later",
    deadline: "2026-09-30",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://ncsc.gov.in/",
    url: "https://ncsc.gov.in/",
    eligibility: { ages: "10-17", nationality: "India", team: "individual or group" },
    components: ["A project on the year's focal theme", "Entry via district coordinator"],
    blurb: "A nationwide project competition on a yearly theme, running from district level up. An IRIS feeder, and one of the few that reaches rural and government schools.",
  },
  {
    id: "jnnsec",
    title: "Jawaharlal Nehru National Science Exhibition for Children (JNNSEC)",
    org: "NCERT",
    type: "Competition",
    fields: ["Engineering", "Research", "Interdisciplinary"],
    region: "India",
    cost: "Free",
    level: "School students",
    window: "School, district and state exhibitions lead to the national round",
    deadline: "2026-09-30",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://ncert.nic.in/",
    url: "https://ncert.nic.in/",
    eligibility: { grades: "school", nationality: "India", route: "via school and district exhibitions" },
    leadsTo: "iris-national-fair",
    components: ["A working model or exhibit on the year's theme"],
    blurb: "NCERT's national science exhibition. Winners are invited toward IRIS, making this a genuine route from a school science fair to ISEF.",
  },
  {
    id: "cbse-science-exhibition",
    title: "CBSE Science Exhibition",
    org: "Central Board of Secondary Education",
    type: "Competition",
    fields: ["Engineering", "Research", "Interdisciplinary"],
    region: "India",
    cost: "Free",
    level: "CBSE school students",
    window: "Regional exhibitions usually autumn, national round after",
    deadline: "2026-10-31",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.cbse.gov.in/",
    url: "https://www.cbse.gov.in/",
    eligibility: { grades: "school", board: "CBSE-affiliated schools" },
    leadsTo: "iris-national-fair",
    components: ["Project or model on the announced theme", "Entry through your school"],
    blurb: "For CBSE schools, an accessible first step - and another feeder into IRIS and the ISEF pathway.",
  },
  {
    id: "atl-marathon",
    title: "ATL Marathon",
    org: "Atal Innovation Mission, NITI Aayog",
    type: "Competition",
    fields: ["Engineering", "Entrepreneurship", "Interdisciplinary"],
    region: "India",
    cost: "Free",
    level: "Classes 6-12",
    window: "Annual challenge, usually announced mid-year",
    deadline: "2026-12-15",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://aim.gov.in/",
    url: "https://aim.gov.in/atl.php",
    eligibility: { grades: "6-12", nationality: "India", note: "open beyond ATL schools in recent editions" },
    components: ["Identify a community problem", "Build a working prototype", "Submit a video/report"],
    blurb: "Build a prototype solving a real community problem. Top innovators get mentorship and incubation support from AIM.",
  },
  {
    id: "sih",
    title: "Smart India Hackathon (SIH)",
    org: "Ministry of Education Innovation Cell",
    type: "Competition",
    fields: ["CS", "Engineering", "Entrepreneurship"],
    region: "India",
    cost: "Free",
    level: "Higher education (some school editions)",
    window: "Registration usually opens mid-year; grand finale later in the year",
    deadline: "2026-09-01",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.sih.gov.in/",
    url: "https://www.sih.gov.in/",
    eligibility: { level: "College students (teams)", nationality: "India", team: true },
    components: ["Team registration through your institution", "Pick a ministry problem statement", "Working solution"],
    blurb: "India's largest hackathon: teams solve real problem statements from ministries and industry, with substantial prizes and hiring attention.",
  },
  {
    id: "tcs-codevita",
    title: "TCS CodeVita",
    org: "Tata Consultancy Services",
    type: "Competition",
    fields: ["CS"],
    region: "India / Global",
    cost: "Free",
    level: "Undergrad",
    window: "Rounds usually run across the second half of the year",
    deadline: "2026-08-31",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.tcscodevita.com/",
    url: "https://www.tcscodevita.com/",
    eligibility: { level: "Undergraduate students", global: true },
    components: ["Online registration", "Any major programming language"],
    blurb: "A global coding contest with a serious India footprint, and a direct interview path at TCS for top performers.",
  },
  {
    id: "flipkart-grid",
    title: "Flipkart GRiD",
    org: "Flipkart",
    type: "Competition",
    fields: ["CS", "Engineering"],
    region: "India",
    cost: "Free",
    level: "Undergrad",
    window: "Usually announced mid-year, multiple rounds",
    deadline: "2026-09-15",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://unstop.com/",
    url: "https://unstop.com/",
    eligibility: { level: "Engineering undergraduates", nationality: "India", team: true },
    components: ["Team registration", "Multi-round technical challenges"],
    blurb: "One of India's biggest campus engineering challenges, with internships and PPOs attached for finalists.",
  },
  {
    id: "madhava-competition",
    title: "Madhava Mathematics Competition",
    org: "Homi Bhabha Centre & partner institutions",
    type: "Competition",
    fields: ["Math"],
    region: "India",
    cost: "Modest fee",
    level: "Undergrad (BSc/BS years 1-3)",
    window: "Exam usually January; registration through your college in autumn",
    deadline: "2026-12-15",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.madhavacompetition.com/",
    url: "https://www.madhavacompetition.com/",
    eligibility: { level: "Undergraduate mathematics students", nationality: "India", enrolVia: "college" },
    components: ["Registration via your college"],
    blurb: "India's main undergraduate mathematics competition - the natural next step after the school olympiad ladder ends.",
  },

  // ======================= SCHOLARSHIPS =======================
  {
    id: "inspire-she",
    title: "INSPIRE Scholarship (SHE)",
    org: "Department of Science & Technology, Government of India",
    type: "Fellowship",
    fields: ["Physics", "Chemistry", "Biology", "Math", "Research"],
    region: "India",
    cost: "Free to apply (scholarship awarded)",
    level: "Undergrad / Postgrad (ages 17-22)",
    window: "Applications usually open around September and close in November",
    deadline: "2026-11-09",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://online-inspire.gov.in/",
    url: "https://online-inspire.gov.in/",
    eligibility: { ages: "17-22", routes: "top 1% in Class 12 board, or top 10,000 JEE/NEET rank, or IISER/NISER/DAE-CBS admission, or NTSE/JBNSTS scholar or International Olympiad medallist", courses: "Natural and Basic Sciences only" },
    components: ["Online application on the INSPIRE portal", "Class 12 marksheet or rank proof", "Scholar/medallist certificate if applying by that route"],
    blurb: "An annual scholarship for basic-science undergraduates, plus a structured summer research attachment. Note the strict subject list: engineering, CS and medicine are excluded.",
  },
  {
    id: "jbnsts",
    title: "Jagadis Bose National Science Talent Search (JBNSTS)",
    org: "JBNSTS, Kolkata",
    type: "Fellowship",
    fields: ["Physics", "Chemistry", "Biology", "Math", "Research"],
    region: "India (West Bengal)",
    cost: "Free",
    level: "Class 12 passed / undergrad entry",
    window: "Application usually early in the year, aptitude test and interview after",
    deadline: "2027-02-28",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.jbnsts.ac.in/",
    url: "https://www.jbnsts.ac.in/",
    eligibility: { residency: "West Bengal", level: "Class 12 / entering undergraduate science" },
    components: ["Application", "Aptitude test", "Interview"],
    blurb: "A prestigious talent search for students from West Bengal. Scholar status also unlocks a direct eligibility route into the INSPIRE Scholarship.",
  },
  {
    id: "dhirubhai-ambani-scholarship",
    title: "Dhirubhai Ambani Scholarship",
    org: "Reliance Foundation",
    type: "Fellowship",
    fields: ["Interdisciplinary"],
    region: "India",
    cost: "Free",
    level: "Class 12 passed, entering undergrad",
    window: "Applications usually open mid-year after board results",
    deadline: "2027-06-30",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.reliancefoundation.org/",
    url: "https://www.reliancefoundation.org/",
    eligibility: { level: "Class 12 passed, entering undergraduate", nationality: "India", meansTested: true },
    components: ["Online application", "Class 12 marks", "Family income proof"],
    blurb: "A merit-cum-means undergraduate scholarship open across streams, with a large number of awards each year.",
  },
  {
    id: "foundation-for-excellence",
    title: "Foundation for Excellence (FFE) Scholarship",
    org: "Foundation for Excellence India Trust",
    type: "Fellowship",
    fields: ["Engineering", "Interdisciplinary"],
    region: "India",
    cost: "Free",
    level: "Undergrad (engineering/medicine)",
    window: "Applications usually open after admission results",
    deadline: "2027-08-31",
    approx: true,
    verifiedAt: "2026-07-22",
    sourceUrl: "https://www.ffe.org/",
    url: "https://www.ffe.org/",
    eligibility: { level: "Undergraduate engineering or medicine", nationality: "India", meansTested: true },
    components: ["Online application", "Admission proof", "Income documentation"],
    blurb: "Need-based support for high-scoring students from low-income families entering professional degrees.",
  },
];
